name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    # - name: Run tests
    #   env:
    #     NDAMAPS_API_KEY: ${{ secrets.NDAMAPS_API_KEY }}
    #   run: swift test -v
